// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASsKN6ZVz5bCugKRJycD0oUBgDYAcs0RA',
    appId: '1:202411345060:web:6d13405b2968abddd2d231',
    messagingSenderId: '202411345060',
    projectId: 'inteligentforms',
    authDomain: 'inteligentforms.firebaseapp.com',
    storageBucket: 'inteligentforms.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoLHwYs_d73QhtQOnh6yK-BDxbdSfh_AI',
    appId: '1:202411345060:android:85ee73c04b0e13f6d2d231',
    messagingSenderId: '202411345060',
    projectId: 'inteligentforms',
    storageBucket: 'inteligentforms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASYfJ6n9QwepclYwUf9BazO6CZbQDh1P8',
    appId: '1:202411345060:ios:435b90979429e925d2d231',
    messagingSenderId: '202411345060',
    projectId: 'inteligentforms',
    storageBucket: 'inteligentforms.appspot.com',
    iosClientId: '202411345060-j3qbof0gj0jrfv0do0s3a8e36kvmma7l.apps.googleusercontent.com',
    iosBundleId: 'gxg.frc.vsy.inteligentForms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASYfJ6n9QwepclYwUf9BazO6CZbQDh1P8',
    appId: '1:202411345060:ios:435b90979429e925d2d231',
    messagingSenderId: '202411345060',
    projectId: 'inteligentforms',
    storageBucket: 'inteligentforms.appspot.com',
    iosClientId: '202411345060-j3qbof0gj0jrfv0do0s3a8e36kvmma7l.apps.googleusercontent.com',
    iosBundleId: 'gxg.frc.vsy.inteligentForms',
  );
}
